/* The JS target. The tcc-js kit only. See js.h.

   The module has five parts: the runtime (the fixed text RUNTIME below), the
   family and constructor tables, one lazy constant for each definition, the
   exports, and with SELFTEST one check for each Eq-typed definition. A core
   term becomes one JS expression: the variable at de Bruijn level L is vL,
   definition N is gN(). The text is ASCII: a string literal escapes each
   other code point. */
#include "js.h"

#include <stdio.h>
#include <string.h>

#include "front/check.h"
#include "json.h"

#define JS_TYPE_MAX 4096u
#define JS_CARRIER_DEPTH 64u

static const char *const RUNTIME[] = {
  "// Generated by langc build --js. Do not edit.",
  "// A Nat is a BigInt in 0 to 2^64-1, a Flag a boolean, a Str a string, a",
  "// function a JS function of one argument, and a type null. Each other value",
  "// is a frozen object with a kind. A Nat overflow gives the value TRAP, as in",
  "// the C evaluator: each strict position passes it up and nothing else reads",
  "// it. encode and the entries throw on it.",
  "const TRAP = Object.freeze({ kind: 'trap' });",
  "const UNIT = Object.freeze({ kind: 'unit' });",
  "const NONE = Object.freeze({ kind: 'none' });",
  "const NIL = Object.freeze({ kind: 'nil' });",
  "const REFL = Object.freeze({ kind: 'refl' });",
  "const MAX = 0xffffffffffffffffn;",
  "const OPTION = 0;",
  "const LIST = 1;",
  "const OVERFLOW = 'a Nat operation overflowed past 2^64-1';",
  "const once = (f) => {",
  "  let done = false;",
  "  let value = null;",
  "  return () => {",
  "    if (!done) {",
  "      value = f();",
  "      done = true;",
  "    }",
  "    return value;",
  "  };",
  "};",
  "const app = (f, x) => (f === TRAP ? TRAP : f(x));",
  "const pair = (first, second) => Object.freeze({ kind: 'pair', first, second });",
  "const inl = (value) => Object.freeze({ kind: 'inl', value });",
  "const inr = (value) => Object.freeze({ kind: 'inr', value });",
  "const some = (value) => Object.freeze({ kind: 'some', value });",
  "const cons = (head, tail) => Object.freeze({ kind: 'cons', head, tail });",
  "const pack = (witness, payload) => Object.freeze({ kind: 'pack', witness, payload });",
  "const ctor = (c, ...a) => {",
  "  const n = CTORS[c].params;",
  "  return Object.freeze({ kind: 'ctor', ctor: c, params: Object.freeze(a.slice(0, n)), fields: Object.freeze(a.slice(n)) });",
  "};",
  "// A list as its items and its end: NIL, or TRAP when a strict step trapped.",
  "const spine = (xs) => {",
  "  const items = [];",
  "  let end = xs;",
  "  while (end.kind === 'cons') {",
  "    items.push(end.head);",
  "    end = end.tail;",
  "  }",
  "  return { items, end };",
  "};",
  "const list = (items, end) => items.reduceRight((tail, x) => cons(x, tail), end);",
  "const first = (p) => (p === TRAP ? TRAP : p.first);",
  "const second = (p) => (p === TRAP ? TRAP : p.second);",
  "const witness = (p) => (p === TRAP ? TRAP : p.witness);",
  "const payload = (p) => (p === TRAP ? TRAP : p.payload);",
  "const proj = (i, x) => (x === TRAP ? TRAP : x.fields[i]);",
  "const either = (f, g, s) => (s === TRAP ? TRAP : app(s.kind === 'inl' ? f : g, s.value));",
  "const optionElim = (z, f, o) => (o === TRAP ? TRAP : o.kind === 'some' ? app(f, o.value) : z);",
  "// The carrier of pure, map, bind and filter: OPTION, LIST, or else Sum (inr).",
  "const pure = (c, x) => (c === OPTION ? some(x) : c === LIST ? cons(x, NIL) : inr(x));",
  "const map = (c, f, m) => {",
  "  if (m === TRAP) return TRAP;",
  "  if (c === OPTION) return m.kind === 'some' ? some(app(f, m.value)) : m;",
  "  if (c !== LIST) return m.kind === 'inr' ? inr(app(f, m.value)) : m;",
  "  const s = spine(m);",
  "  return list(s.items.map((x) => app(f, x)), s.end);",
  "};",
  "const bind = (c, m, f) => {",
  "  if (m === TRAP) return TRAP;",
  "  if (c === OPTION) return m.kind === 'some' ? app(f, m.value) : m;",
  "  if (c !== LIST) return m.kind === 'inr' ? app(f, m.value) : m;",
  "  const s = spine(m);",
  "  const out = [];",
  "  for (const x of s.items) {",
  "    const r = spine(app(f, x));",
  "    r.items.forEach((y) => out.push(y));",
  "    if (r.end !== NIL) return list(out, r.end);",
  "  }",
  "  return list(out, s.end);",
  "};",
  "const filter = (c, p, m) => {",
  "  if (m === TRAP) return TRAP;",
  "  if (c !== LIST) {",
  "    const keep = m.kind === 'some' ? app(p, m.value) : true;",
  "    return keep === TRAP ? TRAP : keep ? m : NONE;",
  "  }",
  "  const s = spine(m);",
  "  const out = [];",
  "  for (const x of s.items) {",
  "    const keep = app(p, x);",
  "    if (keep === TRAP) return list(out, TRAP);",
  "    if (keep) out.push(x);",
  "  }",
  "  return list(out, s.end);",
  "};",
  "const foldNat = (step, z, n) => {",
  "  if (n === TRAP) return TRAP;",
  "  let acc = z;",
  "  for (let k = 0n; k < n; k++) acc = app(step, acc);",
  "  return acc;",
  "};",
  "const foldList = (f, z, xs) => {",
  "  const s = spine(xs);",
  "  return s.items.reduceRight((acc, x) => app(app(f, x), acc), s.end === TRAP ? TRAP : z);",
  "};",
  "const unfold = (g, limit, seed) => {",
  "  if (limit === TRAP) return TRAP;",
  "  const out = [];",
  "  let s = seed;",
  "  for (let left = limit; left > 0n; left--) {",
  "    const r = app(g, s);",
  "    if (r.kind === 'none') return list(out, NIL);",
  "    const p = r.kind === 'some' ? r.value : r;",
  "    if (p === TRAP) return list(out, TRAP);",
  "    out.push(p.first);",
  "    s = p.second;",
  "  }",
  "  return list(out, NIL);",
  "};",
  "// A case takes the fields in order; a recursive field is folded first.",
  "const foldFamily = (family, ...a) => {",
  "  const cases = a.slice(0, -1);",
  "  const go = (v) => {",
  "    if (v === TRAP) return TRAP;",
  "    const info = CTORS[v.ctor];",
  "    const k = cases[v.ctor - FAMILIES[family].first];",
  "    return v.fields.reduce((acc, x, i) => app(acc, info.rec[i] ? go(x) : x), k);",
  "  };",
  "  return go(a[a.length - 1]);",
  "};",
  "const nat = (r) => (r > MAX ? TRAP : r);",
  "const natAdd = (x, y) => (x === TRAP || y === TRAP ? TRAP : nat(x + y));",
  "const natSub = (x, y) => (x === TRAP || y === TRAP ? TRAP : x > y ? x - y : 0n);",
  "const natMul = (x, y) => (x === TRAP || y === TRAP ? TRAP : nat(x * y));",
  "const natEq = (x, y) => (x === TRAP || y === TRAP ? TRAP : x === y);",
  "const natLe = (x, y) => (x === TRAP || y === TRAP ? TRAP : x <= y);",
  "const flagIf = (b, yes, no) => (b === TRAP ? TRAP : b ? yes : no);",
  "const strEq = (x, y) => (x === TRAP || y === TRAP ? TRAP : x === y);",
  "const showNat = (n) => (n === TRAP ? TRAP : n.toString());",
  "const symm = (e) => (e === TRAP ? TRAP : REFL);",
  "const trans = (d, e) => (d === TRAP || e === TRAP ? TRAP : REFL);",
  "const cong = (f, e) => (e === TRAP ? TRAP : REFL);",
  "const transport = (p, e, u) => (e === TRAP ? TRAP : u);",
  "// encode: the JSON text of a value, the same bytes as `langc build --json`.",
  "const quote = (s) => {",
  "  let out = '\"';",
  "  for (const ch of s) {",
  "    const c = ch.codePointAt(0);",
  "    out += c < 32 || c === 34 || c === 92 ? '\\\\u' + c.toString(16).padStart(4, '0') : ch;",
  "  }",
  "  return out + '\"';",
  "};",
  "const wraps = (v) => v !== null && typeof v === 'object' && (v.kind === 'none' || v.kind === 'some' || v.kind === 'refl');",
  "const encodeList = (v) => {",
  "  const s = spine(v);",
  "  return s.end === NIL ? '[' + s.items.map((x) => encode(x)).join(',') + ']' : encode(s.end);",
  "};",
  "const encodeCtor = (v) => {",
  "  const info = CTORS[v.ctor];",
  "  const family = FAMILIES[info.family];",
  "  if (family.enumeration) return quote(info.name);",
  "  const tag = family.count === 1 ? [] : ['\"tag\":' + quote(info.name)];",
  "  return '{' + tag.concat(v.fields.map((x, i) => quote(info.fields[i]) + ':' + encode(x))).join(',') + '}';",
  "};",
  "const encodeInstance = (i) => '{\"name\":' + quote(i.name) + ',\"type\":' + quote(i.type) + ',\"value\":' + encode(i.value) + '}';",
  "const encodeObject = (v) => {",
  "  switch (v.kind) {",
  "    case 'trap': throw new RangeError('EVAL_OVERFLOW: ' + OVERFLOW);",
  "    case 'unit': return '{}';",
  "    case 'none': return 'null';",
  "    case 'refl': return 'null';",
  "    case 'some': return wraps(v.value) ? '{\"some\":' + encode(v.value) + '}' : encode(v.value);",
  "    case 'pair': return '{\"first\":' + encode(v.first) + ',\"second\":' + encode(v.second) + '}';",
  "    case 'inl': return '{\"inl\":' + encode(v.value) + '}';",
  "    case 'inr': return '{\"inr\":' + encode(v.value) + '}';",
  "    case 'nil': return '[]';",
  "    case 'cons': return encodeList(v);",
  "    case 'pack': return '{\"witness\":' + encode(v.witness) + ',\"payload\":' + encode(v.payload) + '}';",
  "    case 'ctor': return encodeCtor(v);",
  "    case 'document': return '{' + quote(v.lang) + ':1,\"instances\":[' + v.instances.map(encodeInstance).join(',') + ']}\\n';",
  "    default: throw new TypeError('encode: an unknown value');",
  "  }",
  "};",
  "const encode = (v) => {",
  "  if (typeof v === 'bigint') return v.toString();",
  "  if (typeof v === 'boolean') return v ? 'true' : 'false';",
  "  if (typeof v === 'string') return quote(v);",
  "  if (v !== null && typeof v === 'object') return encodeObject(v);",
  "  throw new TypeError('encode: a type or a function has no JSON form');",
  "};",
  "// The selftest equality: the C normal forms of two closed values of a",
  "// carrier with no function inside are equal exactly when these are.",
  "const same = (a, b) => {",
  "  if (a === b) return true;",
  "  if (a === null || b === null || typeof a !== 'object' || typeof b !== 'object' || a.kind !== b.kind) return false;",
  "  switch (a.kind) {",
  "    case 'pair': return same(a.first, b.first) && same(a.second, b.second);",
  "    case 'inl': return same(a.value, b.value);",
  "    case 'inr': return same(a.value, b.value);",
  "    case 'some': return same(a.value, b.value);",
  "    case 'pack': return same(a.witness, b.witness) && same(a.payload, b.payload);",
  "    case 'ctor': return a.ctor === b.ctor && a.params.every((x, i) => same(x, b.params[i])) && a.fields.every((x, i) => same(x, b.fields[i]));",
  "    case 'cons': {",
  "      const s = spine(a);",
  "      const t = spine(b);",
  "      return s.items.length === t.items.length && s.items.every((x, i) => same(x, t.items[i])) && same(s.end, t.end);",
  "    }",
  "    default: return false;",
  "  }",
  "};",
  "const check = (name, left, right) => {",
  "  if (!same(left(), right())) throw new Error('selftest: ' + name + ': the two sides differ');",
  "};",
  "// An entry: params is a string of N (a BigInt) and F (a boolean), one for",
  "// each argument; the result is a BigInt (N) or a boolean (F).",
  "const entry = (name, params, result, f) => {",
  "  const run = (...args) => {",
  "    if (args.length !== params.length) throw new TypeError(name + ': wants ' + params.length + ' arguments');",
  "    args.forEach((a, i) => {",
  "      const flag = params[i] === 'F';",
  "      if (flag ? typeof a !== 'boolean' : typeof a !== 'bigint' || a < 0n || a > MAX)",
  "        throw new TypeError(name + ': argument ' + (i + 1) + ' is not a ' + (flag ? 'Flag (a boolean)' : 'Nat (a BigInt in 0 to 2^64-1)'));",
  "    });",
  "    const r = args.reduce((g, a) => app(g, a), f());",
  "    if (r === TRAP) throw new RangeError('EVAL_OVERFLOW: ' + name + ': ' + OVERFLOW);",
  "    return r;",
  "  };",
  "  run.params = params;",
  "  run.result = result;",
  "  return Object.freeze(run);",
  "};",
};

typedef enum {
  JS_CONST, /* the name alone; the arguments are types or there are none */
  JS_CALL,  /* name(arguments) */
  JS_LEAD   /* name(number, arguments): the carrier, family, constructor or field */
} Shape;

typedef struct {
  Machine *m;
  const char *def; /* the current definition, for diagnostics */
  char *data;
  size_t len;
  size_t cap;
} Js;

static int put_n(Js *o, const char *s, size_t n) {
  if (o->len + n >= o->cap) {
    size_t cap = o->cap == 0 ? 4096u : o->cap;
    char *next;
    while (cap <= o->len + n)
      cap *= 2u;
    next = arena_alloc(o->m->arena, cap);
    if (next == NULL)
      return diag_fail(o->m->diag, "OOM", o->def, "the arena limit is reached");
    if (o->len > 0)
      memcpy(next, o->data, o->len);
    o->data = next;
    o->cap = cap;
  }
  memcpy(o->data + o->len, s, n);
  o->len += n;
  return 1;
}

static int put(Js *o, const char *s) {
  return put_n(o, s, strlen(s));
}

static int put_u64(Js *o, uint64_t n) {
  char num[24];
  snprintf(num, sizeof num, "%llu", (unsigned long long)n);
  return put(o, num);
}

static int internal(Js *o, const char *what) {
  return diag_fail(o->m->diag, "INTERNAL", o->def, "the JS writer found %s", what);
}

/* The byte count of the UTF-8 sequence that starts with C, or 0. */
static size_t utf8_width(unsigned c) {
  if (c < 0x80u)
    return 1;
  if (c >= 0xc2u && c <= 0xdfu)
    return 2;
  if (c >= 0xe0u && c <= 0xefu)
    return 3;
  return c >= 0xf0u && c <= 0xf4u ? 4 : 0;
}

/* The code point at S[*AT] in strict UTF-8 (no overlong form, no surrogate,
   at most U+10FFFF), or -1. Moves *AT past it. */
static long utf8_next(const unsigned char *s, size_t len, size_t *at) {
  static const unsigned long LEAST[5] = {0, 0, 0x80u, 0x800u, 0x10000u};
  size_t n = utf8_width(s[*at]);
  unsigned long cp;
  size_t i;
  if (n == 0 || *at + n > len)
    return -1;
  cp = n == 1 ? s[*at] : s[*at] & (0xffu >> (n + 1u));
  for (i = 1; i < n; i++) {
    if ((s[*at + i] & 0xc0u) != 0x80u)
      return -1;
    cp = cp << 6 | (s[*at + i] & 0x3fu);
  }
  if (cp < LEAST[n] || cp > 0x10ffffu || (cp >= 0xd800u && cp <= 0xdfffu))
    return -1;
  *at += n;
  return (long)cp;
}

static int put_unit(Js *o, unsigned long u) {
  char esc[8];
  snprintf(esc, sizeof esc, "\\u%04lx", u);
  return put(o, esc);
}

static int put_code_point(Js *o, unsigned long cp) {
  char c = (char)cp;
  if (cp >= 0x20u && cp < 0x7fu && cp != '\'' && cp != '\\')
    return put_n(o, &c, 1);
  if (cp <= 0xffffu)
    return put_unit(o, cp);
  return put_unit(o, 0xd800u + ((cp - 0x10000u) >> 10)) && put_unit(o, 0xdc00u + ((cp - 0x10000u) & 0x3ffu));
}

/* A JS string literal of the UTF-8 bytes S. A JS string holds code points,
   so bytes that are not UTF-8 are refused (strEq compares bytes in C and
   code units in JS; the two agree on UTF-8). */
static int put_js_string(Js *o, const char *s, size_t len) {
  const unsigned char *b = (const unsigned char *)s;
  size_t at = 0;
  int ok = put(o, "'");
  while (ok && at < len) {
    long cp = utf8_next(b, len, &at);
    if (cp < 0)
      return diag_fail(o->m->diag, "JS_UTF8", o->def, "a string holds bytes that are not UTF-8, which a JS string cannot hold");
    ok = put_code_point(o, (unsigned long)cp);
  }
  return ok && put(o, "'");
}

static int put_name(Js *o, const char *name) {
  return put_js_string(o, name, strlen(name));
}

static Shape op_shape(Op op, const char **name) {
  switch (op) {
  case OP_NAT:
  case OP_FLAG:
  case OP_STR:
  case OP_UNIT:
  case OP_PROD:
  case OP_SUM:
  case OP_OPTION:
  case OP_LIST:
  case OP_EQ:
  case OP_FAMILY:
    *name = "null";
    return JS_CONST;
  case OP_UNIT_VAL:
    *name = "UNIT";
    return JS_CONST;
  case OP_FLAG_YES:
    *name = "true";
    return JS_CONST;
  case OP_FLAG_NO:
    *name = "false";
    return JS_CONST;
  case OP_NONE:
    *name = "NONE";
    return JS_CONST;
  case OP_NIL:
    *name = "NIL";
    return JS_CONST;
  case OP_REFL:
    *name = "REFL";
    return JS_CONST;
  case OP_PAIR:
    *name = "pair";
    return JS_CALL;
  case OP_INL:
    *name = "inl";
    return JS_CALL;
  case OP_INR:
    *name = "inr";
    return JS_CALL;
  case OP_SOME:
    *name = "some";
    return JS_CALL;
  case OP_CONS:
    *name = "cons";
    return JS_CALL;
  case OP_PACK:
    *name = "pack";
    return JS_CALL;
  case OP_CTOR:
    *name = "ctor";
    return JS_LEAD;
  case OP_FIRST:
    *name = "first";
    return JS_CALL;
  case OP_SECOND:
    *name = "second";
    return JS_CALL;
  case OP_EITHER:
    *name = "either";
    return JS_CALL;
  case OP_OPTION_ELIM:
    *name = "optionElim";
    return JS_CALL;
  case OP_PURE:
    *name = "pure";
    return JS_LEAD;
  case OP_MAP:
    *name = "map";
    return JS_LEAD;
  case OP_BIND:
    *name = "bind";
    return JS_LEAD;
  case OP_FOLD_NAT:
    *name = "foldNat";
    return JS_CALL;
  case OP_FOLD_LIST:
    *name = "foldList";
    return JS_CALL;
  case OP_FOLD_FAMILY:
    *name = "foldFamily";
    return JS_LEAD;
  case OP_UNFOLD:
    *name = "unfold";
    return JS_CALL;
  case OP_FILTER:
    *name = "filter";
    return JS_LEAD;
  case OP_WITNESS:
    *name = "witness";
    return JS_CALL;
  case OP_PAYLOAD:
    *name = "payload";
    return JS_CALL;
  case OP_SYMM:
    *name = "symm";
    return JS_CALL;
  case OP_TRANS:
    *name = "trans";
    return JS_CALL;
  case OP_TRANSPORT:
    *name = "transport";
    return JS_CALL;
  case OP_CONG:
    *name = "cong";
    return JS_CALL;
  case OP_NAT_ADD:
    *name = "natAdd";
    return JS_CALL;
  case OP_NAT_SUB:
    *name = "natSub";
    return JS_CALL;
  case OP_NAT_MUL:
    *name = "natMul";
    return JS_CALL;
  case OP_NAT_EQ:
    *name = "natEq";
    return JS_CALL;
  case OP_NAT_LE:
    *name = "natLe";
    return JS_CALL;
  case OP_FLAG_IF:
    *name = "flagIf";
    return JS_CALL;
  case OP_STR_EQ:
    *name = "strEq";
    return JS_CALL;
  case OP_SHOW_NAT:
    *name = "showNat";
    return JS_CALL;
  case OP_PROJ:
    *name = "proj";
    return JS_LEAD;
  }
  *name = "null";
  return JS_CONST;
}

static int emit(Js *o, uint32_t depth, const Core *c);

/* The arguments are evaluated left to right before the call, as in eval.c. */
static int emit_op(Js *o, uint32_t depth, const Core *c) {
  const char *name = NULL;
  Shape shape = op_shape(c->op, &name);
  uint32_t i;
  int ok = 0;
  switch (shape) {
  case JS_CONST:
    return put(o, name);
  case JS_CALL:
    ok = put(o, name) && put(o, "(");
    break;
  case JS_LEAD:
    ok = put(o, name) && put(o, "(") && put_u64(o, c->op == OP_PROJ ? c->field : c->inst);
    break;
  }
  for (i = 0; ok && i < c->argc; i++)
    ok = ((shape == JS_CALL && i == 0) || put(o, ", ")) && emit(o, depth, c->args[i]);
  return ok && put(o, ")");
}

/* DEPTH is the number of binders around C. */
static int emit(Js *o, uint32_t depth, const Core *c) {
  switch (c->kind) {
  case CORE_VAR:
    if (c->index >= depth)
      return internal(o, "a free variable");
    return put(o, "v") && put_u64(o, depth - 1u - c->index);
  case CORE_GLOBAL:
    return put(o, "g") && put_u64(o, c->index) && put(o, "()");
  case CORE_NAT:
    return put_u64(o, c->nat) && put(o, "n");
  case CORE_STR:
    return put_js_string(o, c->name, (size_t)c->nat);
  case CORE_TRAP:
    return put(o, "TRAP");
  case CORE_UNIV:
  case CORE_PI:
  case CORE_SIGMA:
    return put(o, "null");
  case CORE_LAM:
    return put(o, "((v") && put_u64(o, depth) && put(o, ") => ") && emit(o, depth + 1u, c->b) && put(o, ")");
  case CORE_APP:
    return put(o, "app(") && emit(o, depth, c->a) && put(o, ", ") && emit(o, depth, c->b) && put(o, ")");
  case CORE_OP:
    return emit_op(o, depth, c);
  }
  return internal(o, "an unknown core term");
}

static int emit_runtime(Js *o) {
  size_t i;
  int ok = 1;
  for (i = 0; ok && i < sizeof RUNTIME / sizeof RUNTIME[0]; i++)
    ok = put(o, RUNTIME[i]) && put(o, "\n");
  return ok;
}

/* 1 when each constructor of F has no field (JSON writes the name). */
static int all_constants(const Machine *m, const FamilyInfo *f) {
  uint32_t i;
  for (i = 0; i < f->ctor_count; i++)
    if (m->ctors[f->first_ctor + i].field_count != 0)
      return 0;
  return 1;
}

static int emit_ctor_row(Js *o, const CtorInfo *ci) {
  uint32_t j;
  int ok = put(o, "  { name: ") && put_name(o, ci->name) && put(o, ", family: ") && put_u64(o, ci->family)
    && put(o, ", params: ") && put_u64(o, o->m->families[ci->family].param_count) && put(o, ", fields: [");
  for (j = 0; ok && j < ci->field_count; j++)
    ok = (j == 0 || put(o, ", ")) && put_name(o, ci->fields[j].name);
  ok = ok && put(o, "], rec: [");
  for (j = 0; ok && j < ci->field_count; j++)
    ok = (j == 0 || put(o, ", ")) && put(o, ci->fields[j].recursive ? "true" : "false");
  return ok && put(o, "] },\n");
}

static int emit_tables(Js *o) {
  const Machine *m = o->m;
  uint32_t i;
  int ok = put(o, "const FAMILIES = [\n");
  for (i = 0; ok && i < m->family_count; i++) {
    const FamilyInfo *f = &m->families[i];
    ok = put(o, "  { name: ") && put_name(o, f->name) && put(o, ", first: ") && put_u64(o, f->first_ctor)
      && put(o, ", count: ") && put_u64(o, f->ctor_count) && put(o, ", enumeration: ")
      && put(o, all_constants(m, f) ? "true" : "false") && put(o, " },\n");
  }
  ok = ok && put(o, "];\nconst CTORS = [\n");
  for (i = 0; ok && i < m->ctor_count; i++)
    ok = emit_ctor_row(o, &m->ctors[i]);
  return ok && put(o, "];\n");
}

/* Each definition is computed when first used, as def_value does. */
static int emit_defs(Js *o) {
  uint32_t i;
  int ok = 1;
  for (i = 0; ok && i < o->m->def_count; i++) {
    const DefInfo *d = &o->m->defs[i];
    o->def = d->name;
    ok = put(o, "const g") && put_u64(o, i) && put(o, " = once(() => ")
      && (d->body == NULL ? put(o, "null") : emit(o, 0, d->body)) && put(o, ");\n");
  }
  return ok;
}

static int emit_instance(Js *o, uint32_t index, char *type_text) {
  const DefInfo *d = &o->m->defs[index];
  o->def = d->name;
  if (!value_print(o->m, NULL, 0, d->type, type_text, JS_TYPE_MAX))
    return internal(o, "an instance type that does not print");
  return put(o, "    Object.freeze({ name: ") && put_name(o, d->name) && put(o, ", type: ")
    && put_name(o, type_text) && put(o, ", value: g") && put_u64(o, index) && put(o, "() }),\n");
}

/* The instance document of the JSON target, its values computed in JS. */
static int emit_document(Js *o, char *type_text) {
  uint32_t i;
  int ok = put(o, "export const document = Object.freeze({\n  kind: 'document',\n  lang: ") && put_name(o, json_lang_name)
    && put(o, ",\n  instances: Object.freeze([\n");
  for (i = 0; ok && i < o->m->def_count; i++)
    ok = !json_is_instance(&o->m->defs[i]) || emit_instance(o, i, type_text);
  return ok && put(o, "  ]),\n});\n");
}

static int emit_entry(Js *o, uint32_t index, const Entry *e) {
  const DefInfo *d = &o->m->defs[index];
  uint32_t k;
  int ok;
  o->def = d->name;
  ok = put(o, "  [") && put_name(o, d->name) && put(o, ", entry(") && put_name(o, d->name) && put(o, ", '");
  for (k = 0; ok && k < e->param_count; k++)
    ok = put(o, e->param_flag[k] ? "F" : "N");
  return ok && put(o, "', '") && put(o, e->result_flag ? "F" : "N") && put(o, "', g") && put_u64(o, index) && put(o, ")],\n");
}

/* The definitions that `langc eval` runs with arguments (all of them, as
   eval_command searches the domain too). */
static int emit_entries(Js *o) {
  uint32_t i;
  int ok = put(o, "export const entries = Object.freeze(Object.fromEntries([\n");
  for (i = 0; ok && i < o->m->def_count; i++) {
    Entry e;
    memset(&e, 0, sizeof e);
    ok = !entry_of(o->m, o->m->defs[i].type, &e) || emit_entry(o, i, &e);
  }
  return ok && put(o, "]));\nexport { encode };\n");
}

static int comparable(Machine *m, const Value *t, uint32_t depth);

/* A field type is in the context of the family parameters, as in check.c. */
static int family_comparable(Machine *m, const Value *t, uint32_t depth) {
  const FamilyInfo *f = &m->families[t->inst];
  const Env *env = NULL;
  uint32_t i;
  uint32_t j;
  int ok = 1;
  for (i = 0; i < f->param_count && i < t->argc; i++)
    env = env_push(m, env, t->args[i]);
  for (i = 0; ok && i < f->ctor_count; i++) {
    const CtorInfo *ci = &m->ctors[f->first_ctor + i];
    for (j = 0; ok && j < ci->field_count; j++)
      ok = ci->fields[j].recursive || comparable(m, eval_core(m, env, ci->fields[j].type), depth + 1u);
  }
  return ok;
}

static int op_comparable(Machine *m, const Value *t, uint32_t depth) {
  switch (t->op) {
  case OP_NAT:
  case OP_FLAG:
  case OP_STR:
  case OP_UNIT:
  case OP_EQ:
    return 1;
  case OP_PROD:
  case OP_SUM:
    return t->argc == 2 && comparable(m, t->args[0], depth + 1u) && comparable(m, t->args[1], depth + 1u);
  case OP_OPTION:
  case OP_LIST:
    return t->argc == 1 && comparable(m, t->args[0], depth + 1u);
  case OP_FAMILY:
    return t->inst < m->family_count && family_comparable(m, t, depth);
  case OP_UNIT_VAL:
  case OP_FLAG_YES:
  case OP_FLAG_NO:
  case OP_PAIR:
  case OP_INL:
  case OP_INR:
  case OP_NONE:
  case OP_SOME:
  case OP_NIL:
  case OP_CONS:
  case OP_PACK:
  case OP_REFL:
  case OP_CTOR:
  case OP_FIRST:
  case OP_SECOND:
  case OP_EITHER:
  case OP_OPTION_ELIM:
  case OP_PURE:
  case OP_MAP:
  case OP_BIND:
  case OP_FOLD_NAT:
  case OP_FOLD_LIST:
  case OP_FOLD_FAMILY:
  case OP_UNFOLD:
  case OP_FILTER:
  case OP_WITNESS:
  case OP_PAYLOAD:
  case OP_SYMM:
  case OP_TRANS:
  case OP_TRANSPORT:
  case OP_CONG:
  case OP_NAT_ADD:
  case OP_NAT_SUB:
  case OP_NAT_MUL:
  case OP_NAT_EQ:
  case OP_NAT_LE:
  case OP_FLAG_IF:
  case OP_STR_EQ:
  case OP_SHOW_NAT:
  case OP_PROJ:
    return 0;
  }
  return 0;
}

/* 1 when the values of type T compare in JS as their normal forms compare in
   C: no function and no type inside. */
static int comparable(Machine *m, const Value *t, uint32_t depth) {
  if (t == NULL || depth >= JS_CARRIER_DEPTH)
    return 0;
  switch (t->kind) {
  case VAL_OP:
    return op_comparable(m, t, depth);
  case VAL_SIGMA:
    return comparable(m, t->dom, depth + 1u) && comparable(m, closure_apply(m, t, val_var(m, 0)), depth + 1u);
  case VAL_NAT:
  case VAL_STR:
  case VAL_TRAP:
  case VAL_UNIV:
  case VAL_LAM:
  case VAL_PI:
  case VAL_VAR:
  case VAL_APP:
  case VAL_STUCK:
    return 0;
  }
  return 0;
}

static int is_test(const DefInfo *d) {
  return d->type != NULL && val_is(d->type, OP_EQ) && d->type->argc == 3;
}

/* Both sides as written in the type (else their normal forms, for a type
   that is Eq only after evaluation). */
static int emit_test(Js *o, const DefInfo *d) {
  Machine *m = o->m;
  const Core *t = d->type_core;
  int direct = t != NULL && t->kind == CORE_OP && t->op == OP_EQ && t->argc == 3;
  const Core *left;
  const Core *right;
  o->def = d->name;
  m->def = d->name;
  m->fuel = EVAL_FUEL_STEPS;
  m->depth = 0;
  if (!comparable(m, d->type->args[0], 0))
    return put(o, "// selftest skips ") && put_name(o, d->name) && put(o, ": its carrier has a function or a type inside\n");
  left = direct ? t->args[1] : quote_value(m, 0, d->type->args[1]);
  right = direct ? t->args[2] : quote_value(m, 0, d->type->args[2]);
  return left != NULL && right != NULL && put(o, "check(") && put_name(o, d->name) && put(o, ", () => ")
    && emit(o, 0, left) && put(o, ", () => ") && emit(o, 0, right) && put(o, ");\n");
}

static int emit_selftest(Js *o) {
  uint32_t i;
  int ok = put(o, "// The selftest: both sides of each Eq-typed definition, evaluated here.\n");
  for (i = 0; ok && i < o->m->def_count; i++)
    ok = !is_test(&o->m->defs[i]) || emit_test(o, &o->m->defs[i]);
  return ok;
}

int js_module(Machine *m, int selftest, const char **text, size_t *len) {
  Js o;
  char *type_text = arena_alloc(m->arena, JS_TYPE_MAX);
  memset(&o, 0, sizeof o);
  o.m = m;
  if (type_text == NULL)
    return diag_fail(m->diag, "OOM", NULL, "the arena limit is reached");
  if (!emit_runtime(&o) || !emit_tables(&o) || !emit_defs(&o) || !emit_document(&o, type_text) || !emit_entries(&o))
    return 0;
  if (selftest && !emit_selftest(&o))
    return 0;
  *text = o.data;
  *len = o.len;
  return 1;
}
